### ISSUE TITLE
Editing a project description does not preserve the project's existing description.

### ISSUE THREAD

**Issue by Darkhax** [Diluv/Diluv-Website#159]
**Description**
When I edit the description of a project the original description is not copied over to the edit page. Instead the text box is empty.

**Reproduction Steps**
When I edit the description of Botany Pots the description section is project description is blank.

1. Go to a project.
2. Click on settings.
3. The description is blank.

**Expected behavior**
I expected the original description which already exists to be copied over to the edit page rather than it being reset.

**Screenshots**
![description](https://user-images.githubusercontent.com/2250798/97957444-1f7b9680-1da3-11eb-9e0f-adce0acf2584.gif)

**Platform:**

-   OS: Win10
-   Browser: Firefox
-   Device: Laptop

**Additional Info**
N/A

**Comment by jaredlll08** [comment]
This was fixed ages ago
