### ISSUE TITLE
Games are misaligned on the front page

### ISSUE THREAD

**Issue by Gamebuster19901** [Diluv/Diluv-Website#162]
**Description**
The games are not aligned correctly under "Popular Games" and "New Games" on the front page.

**Reproduction Steps**
N/A

**Expected behavior**
The games should be centered with the text under "Popular Games" and "New Games".

**Screenshots**
![image](https://user-images.githubusercontent.com/7155747/99943198-e77ec800-2d3e-11eb-8ddd-418472b682a5.png)

**Platform:**
- OS: Ubuntu 20.04.1 LTS
- Web browser: Chromium

**Additional Info**
- A 4k display may be required to reproduce this bug

**Comment by jaredlll08** [comment]
So this specific issue has been fixed, however I don't want to close this issue right now as this is probably also affecting all the other images on the site, so I'll close it once I've gone through them all and fixed them

**Comment by jaredlll08** [comment]
I believe this has now been fixed, please let me know if you run into anything like it again ^^
