### ISSUE TITLE
Some CSS is being unintentionally purged.

### ISSUE THREAD

**Issue by Darkhax** [Diluv/Diluv-Website#164]
**Description**
Some of the CSS is being purged. This makes things show up without their expected CSS properties.

**Reproduction Steps**

1. Go to [Bookshelf](https://diluv.dev/games/minecraft-je/mods/bookshelf)
2. HTML inspect the description (Specifically the text saying NOTICE)
3. The tag has the CSS class `admonition-heading` but this class is not present.

**Expected behavior**
The CSS should be there. The text should have the CSS for our notices.

**Screenshots**
![image](https://user-images.githubusercontent.com/2250798/101786086-6de42980-3af5-11eb-9c9d-beb133539ae8.png)

**Platform:**

-   OS: Win10
-   Browser: FireFox
-   Device: Desktop

**Additional Info**
Possibly related to PurgeCSS. This has only been observed on notices such as admonitions and the project notice warnings like under review.

**Comment by jaredlll08** [comment]
This has been fixed

**Comment by Darkhax** [comment]
This CSS seems to still be broken on the current staging?

**Comment by lclc98** [comment]
Should be fixed with latest commit, reopen issue if still an issue.

**Comment by Darkhax** [comment]
This is confirmed to be fixed :shipit:
