### ISSUE TITLE
Unable to create projects / No Tags

### ISSUE THREAD

**Issue by Darkhax** [Diluv/Diluv-Website#174]
**Description**
When creating a new project or editing an existing one no tags are shown. A project needs at least one tag so this prevents projects from being created.

**Reproduction Steps**
Describe how this happened

1. Go to the project creation page.
2. Click on the tags section.
3. There are no tags.

**Expected behavior**
The tags should be shown.

**Screenshots**

**Platform:** 

-   OS: Win10
-   Browser: FireFox
-   Device: Desktop

**Additional Info**
N/A

**Comment by jaredlll08** [comment]
A tag has been created.
